version: '3.1'
services:
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80
    depends_on:
      - mysql
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./adminer.css:/var/www/html/adminer.css
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  mysqldata: {}
